// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Production.Models;

namespace Production.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Production.Models.Cart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("item_name");

                    b.Property<int>("items_amount");

                    b.Property<float>("sum");

                    b.Property<string>("user_id");

                    b.HasKey("id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Production.Models.Manufacturer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Production.Models.Materials", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("amount");

                    b.Property<int>("m_id");

                    b.Property<string>("materialname");

                    b.HasKey("id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Production.Models.Orders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("items");

                    b.Property<float>("summa");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Production.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("amount");

                    b.Property<string>("description");

                    b.Property<int>("m_id");

                    b.Property<int>("material");

                    b.Property<int>("material_id");

                    b.Property<string>("p_name");

                    b.Property<float>("price");

                    b.HasKey("id");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
